
Skip to content
sn99 /
wasm-template-rust

Code
Issues
Pull requests
Actions
Projects
Wiki

More
wasm-template-rust/.travis.yml
@sn99
sn99 initial
History
1 contributor
62 lines (55 sloc) 1.59 KB
language: rust
sudo: false

INSTALL_NODE_VIA_NVM: &INSTALL_NODE_VIA_NVM
                        |
                        rustup target add wasm32-unknown-unknown
                        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
                        source ~/.nvm/nvm.sh
                        nvm install 10

# Cache `cargo install`ed tools, but don't cache the project's `target`
# directory (which ends up over-caching and filling all disk space!)
cache:
  directories:
    - /home/travis/.cargo

script:
  - cd crate-wasm
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cd ..

matrix:
  allow_failures:
    - name: Tests
  include:
    - name: Page
      rust: stable
      before_script:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      install:
        - *INSTALL_NODE_VIA_NVM
      script:
        - mkdir -p docs
        - rm -rf ./docs/*
        - cd crate-wasm
        - wasm-pack build
        - cd ..
        - cd www && npm install
        - npm run build
        - mv ./dist/* ..
      deploy:
        provider: pages
        skip-cleanup: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
        local-dir: docs
        keep-history: false

    - name: Tests
      env: RUST_BACKTRACE=1
      rust: stable
      addons:
        firefox: latest
        chrome: stable
      before_script:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      install:
        - *INSTALL_NODE_VIA_NVM
      script:
        - cd crate-wasm
        - cargo test --all
        - cargo test --all --target wasm32-unknown-unknown
        - cd ..

notifications:
  email:
    on_success: never

    © 2021 GitHub, Inc.
    Terms
    Privacy
    Security
    Status
    Docs

    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

